//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viajar360BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int id_chat { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string mail { get; set; }
        public Nullable<bool> respondido { get; set; }
    }
}
