//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viajar360BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int id_comentario { get; set; }
        public int id_tema { get; set; }
        public byte[] fecha_hora { get; set; }
        public string mensaje { get; set; }
        public int id_usuario { get; set; }
        public int reportes { get; set; }
    }
}
