//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viajar360BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentarios
    {
        public int id_comentario { get; set; }
        public int id_tema { get; set; }
        public System.DateTime fecha_hora { get; set; }
        public string mensaje { get; set; }
        public int id_usuario { get; set; }
        public int reportes { get; set; }
    }
}
