//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viajar360BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_usuario { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string mail { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public string localidad { get; set; }
        public string provincia { get; set; }
        public string foto { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha_kick { get; set; }
        public string motivo { get; set; }
        public bool reset_password { get; set; }
        public string modificaciones { get; set; }
        public string salt { get; set; }
    }
}
