//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viajar360BackEnd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int id_chat { get; set; }
        public string apellido { get; set; }
        public string nombre { get; set; }
        public string mensaje { get; set; }
        public Nullable<System.DateTime> fecha_hora { get; set; }
        public string mail { get; set; }
    }
}
